/* =============================================================================
 *  js/data.js  -  the whole family.
 *
 *  Written out by the in-page editor on 2026-08-29.
 *  Safe to keep editing by hand: the format is exactly the same either way.
 *
 *  families : one entry per surname, with its colour
 *  people   : one entry per person   (family = the family they were BORN into)
 *  unions   : one entry per marriage (children only connect through these)
 *
 *  alive: false marks somebody who has died, and is the only time the
 *  field appears. No field means living, which is true of nearly
 *  everybody. Birth and death years are optional detail either way.
 *
 *  Full guide: docs/EDITING.md
 * ========================================================================== */

window.FAMILY = {

  meta: { title: "Makani Family Tree",
    subtitle: "మాకని వంశ వృక్షం · five generations", updated: "2026-08-22" },

  config: { photoDir: "photos", autoPhotos: true, anchorPreference: "m",
    showPlaceholders: true },

  families: {
    makani: { name: "Makani", telugu: "మాకని", color: "#4f46e5",
      notes: "The main line of this chart." },
    macha: { name: "Macha", telugu: "మాచ", color: "#0d9488",
      notes: "Twice allied to the Makani line: two Macha sisters married two Makani brothers, making their children double first cousins." },
    mutyala: { name: "Mutyala", telugu: "ముత్యాల", color: "#d97706",
      notes: "Joined by the marriage of Sai Priyanka Makani to Thrinadh Mutyala." },
    tbd: { name: "Not yet recorded", color: "#64748b",
      notes: "Placeholder for people whose birth surname is still unknown. When you learn it, add a real family here and repoint them." },
    emani: { name: "Emani", color: "#be123c" },
    sunkara: { name: "Sunkara", color: "#7c3aed" },
    pulagam: { name: "Pulagam", color: "#0369a1" },
    kandha: { name: "Kandha", color: "#65a30d" },
    maddala: { name: "Maddala", color: "#c026d3" },
    Chanthati: { name: "Chanthati", color: "#ea580c" },
    rao: { name: "Rao", color: "#0f766e" },
    rayappareddy: { name: "Rayappareddy", color: "#9333ea" },
    apparao: { name: "Apparao", color: "#047857" },
    modugu: { name: "Modugu", color: "#0d9488" },
    devisetti: { name: "Devisetti", color: "#d97706" },
    nanduri: { name: "Nanduri", color: "#be123c" },
    thota: { name: "Thota", color: "#7c3aed" },
    varre: { name: "Varre", color: "#0369a1" },
    reddy: { name: "Reddy", color: "#65a30d" },
    bhandhar: { name: "Bhandhar", color: "#c026d3" },
    veerisetti: { name: "Veerisetti", color: "#ea580c" },
    kosanam: { name: "Kosanam", color: "#0f766e" },
    bhandar: { name: "Bhandar", color: "#9333ea" },
    gaurisetti: { name: "Gaurisetti", color: "#047857" }
  },

  people: [
    /* ---- generation 1 ---- */
    { id: "macha-g1-f", name: "Ramaswamy Macha", family: "macha", gen: 1,
      sex: "m", order: 1, todo: "name unknown" },
    { id: "makani-narayanamma", name: "Narayanamma Devisetti",
      family: "makani", marriedInto: "devisetti", gen: 1, sex: "f", order: 3,
      alive: false },
    { id: "makani-g1-f", name: "Venkata Swamy Makani", family: "makani",
      gen: 1, sex: "m" },
    { id: "makani-g1-m", name: "Anasuyamma Makani", family: "sunkara",
      marriedInto: "makani", gen: 1, sex: "f" },
    { id: "macha-g1-m", name: "Raghavamma Macha", family: "makani",
      marriedInto: "macha", gen: 1, sex: "f" },

    /* ---- generation 2 ---- */
    { id: "makani-nageshwara", name: "Nageshwara Rao Makani",
      family: "makani", gen: 2, sex: "m", order: 1, alive: false },
    { id: "maddala-jayalakshmi", name: "Jayalakshmi Maddala", family: "tbd",
      marriedInto: "maddala", gen: 2, sex: "f", order: 1, todo: "birth family" },
    { id: "makani-ramachandra-rao", name: "Ramachandra Rao Makani",
      family: "makani", gen: 2, sex: "m", order: 2, alive: false,
      title: "Thathayya", notes: "Father of the six Makani brothers." },
    { id: "Chanthati-seetharathnamma", name: "Seetharathnamma Chanthati",
      family: "tbd", marriedInto: "Chanthati", gen: 2, sex: "f", order: 2 },
    { id: "makani-sanjeeva", name: "Sanjeeva Rao Makani", family: "makani",
      gen: 2, sex: "m", order: 3 },
    { id: "sunkara-chitamma", name: "Chitamma Sunkara", family: "makani",
      marriedInto: "sunkara", gen: 2, sex: "f", order: 4, alive: false },
    { id: "makani-sarojini", name: "Sarojini Gaurisetti", family: "makani",
      marriedInto: "gaurisetti", gen: 2, sex: "f", order: 5 },
    { id: "tbd-padmavathi", name: "Padmavathi Makani", family: "kandha",
      marriedInto: "makani", gen: 2, sex: "f", alive: false, title: "Nanamma" },
    { id: "macha-thatha", name: "Krishna Rao Macha", family: "macha", gen: 2,
      sex: "m", death: "2024", alive: false, title: "Thathagaru" },
    { id: "tbd-jayalakshmi", name: "Jayalakshmi Macha", family: "tbd",
      marriedInto: "macha", gen: 2, sex: "f", death: "2019", alive: false,
      title: "Ammamma", notes: "Known in the family as Ammamma.",
      todo: "family name" },
    { id: "tbd-vijayamma", name: "Vijayamma Makani", family: "pulagam",
      marriedInto: "makani", gen: 2, sex: "f", alive: false },
    { id: "tbd-sathyavathi", name: "Sathyavathi Makani", family: "sunkara",
      marriedInto: "makani", gen: 2, sex: "f" },
    { id: "tbd-apparao", name: "Apparao Chanthati", family: "Chanthati",
      gen: 2, sex: "u", alive: false, todo: "birth family (intiperu)" },
    { id: "tbd-veera", name: "Veera Rajeshwara Rao Maddala",
      family: "maddala", gen: 2, sex: "m" },
    { id: "tbd-bhushan", name: "Bhushan Rao Sunkara", family: "sunkara",
      gen: 2, sex: "m" },
    { id: "rao-nagabhushan", name: "Nagabhushan Rao Gaurisetti",
      family: "gaurisetti", gen: 2, sex: "u" },

    /* ---- generation 3 ---- */
    { id: "makani-venkateshwara-rao", name: "Venkateshwara Rao Makani",
      family: "makani", gen: 3, sex: "m", order: 1 },
    { id: "macha-padmaja", name: "Padmaja Makani", family: "macha",
      marriedInto: "makani", gen: 3, sex: "f", order: 1,
      notes: "Elder sister of Suneetha. Married Satyanarayana Makani." },
    { id: "makani-ramamohan", name: "Ramamohan Makani", family: "makani",
      gen: 3, sex: "m", order: 1 },
    { id: "Chanthati-nagamani", name: "Nagamani", family: "Chanthati", gen: 3,
      sex: "f", order: 1 },
    { id: "maddala-srinivas", name: "Srinivas Maddala", family: "maddala",
      gen: 3, sex: "m", order: 1 },
    { id: "sunkara-srinu", name: "Srinu", family: "sunkara", gen: 3, sex: "f",
      order: 1 },
    { id: "makani-anu", name: "Anu Bhandhar", family: "makani",
      marriedInto: "bhandhar", gen: 3, sex: "f", order: 1 },
    { id: "makani-neelima-2", name: "Neelima", family: "gaurisetti", gen: 3,
      sex: "f", order: 1 },
    { id: "makani-chandrashekhar", name: "Chandrashekhar Makani",
      family: "makani", gen: 3, sex: "m", order: 2 },
    { id: "macha-suneetha", name: "Suneetha Makani", family: "macha",
      marriedInto: "makani", gen: 3, sex: "f", order: 2,
      notes: "Married Nagarjuna Sagar Makani." },
    { id: "makani-madhumohan", name: "Madhumohan Makani", family: "makani",
      gen: 3, sex: "m", order: 2 },
    { id: "Chanthati-indira", name: "Indira", family: "Chanthati", gen: 3,
      sex: "f", order: 2 },
    { id: "maddala-shekhar", name: "Shekhar Maddala", family: "maddala",
      gen: 3, sex: "m", order: 2 },
    { id: "sunkara-ashok", name: "Ashok Sunkara", family: "sunkara", gen: 3,
      sex: "m", order: 2 },
    { id: "makani-meena", name: "Meena", family: "makani", gen: 3, sex: "f",
      order: 2 },
    { id: "makani-praveen", name: "Praveen Gaurisetti", family: "gaurisetti",
      gen: 3, sex: "m", order: 2 },
    { id: "makani-satyanarayana", name: "Satyanarayana Makani",
      family: "makani", gen: 3, sex: "m", order: 3 },
    { id: "macha-ramesh", name: "Ramesh Macha", family: "macha", gen: 3,
      sex: "m", order: 3, death: "2025", alive: false },
    { id: "makani-vijayanand", name: "Vijayanand Makani", family: "makani",
      gen: 3, sex: "m", order: 3 },
    { id: "Chanthati-usha", name: "Usha", family: "Chanthati", gen: 3,
      sex: "f", order: 3 },
    { id: "maddala-ramakanth", name: "Ramakanth Maddala", family: "maddala",
      gen: 3, sex: "m", order: 3 },
    { id: "makani-bujji", name: "Suguna Kumari (Suneetha)", family: "makani",
      gen: 3, sex: "f", order: 3 },
    { id: "makani-ramakrishna-sr", name: "Ramakrishna Makani",
      family: "makani", gen: 3, sex: "m", order: 4, death: "~1970",
      alive: false },
    { id: "Chanthati-chanti-amma", name: "Chantiamma", family: "Chanthati",
      gen: 3, sex: "f", order: 4 },
    { id: "makani-baby-2", name: "Hemakumari Kosanam (Baby)",
      family: "makani", gen: 3, sex: "f", order: 4 },
    { id: "makani-nagarjuna-sagar", name: "Nagarjuna Sagar Makani",
      family: "makani", gen: 3, sex: "m", order: 5 },
    { id: "Chanthati-bujjiamma", name: "Bujjiamma", family: "Chanthati",
      gen: 3, sex: "f", order: 5 },
    { id: "makani-harikrishna", name: "Harikrishna Makani", family: "makani",
      gen: 3, sex: "m", order: 6 },
    { id: "Chanthati-jagan", name: "Jagan Mohan Chanthati",
      family: "Chanthati", gen: 3, sex: "m", order: 6, alive: false },
    { id: "Chanthati-nageswar", name: "Nageshwar Rao Chanthati",
      family: "Chanthati", gen: 3, sex: "m", order: 7, alive: false },
    { id: "tbd-latha", name: "Latha Makani", family: "varre",
      marriedInto: "makani", gen: 3, sex: "f", todo: "birth family (intiperu)" },
    { id: "tbd-sarada", name: "Sarada Makani", family: "thota",
      marriedInto: "makani", gen: 3, sex: "f", todo: "birth family (intiperu)" },
    { id: "tbd-nalini", name: "Nalini Macha", family: "tbd",
      marriedInto: "macha", gen: 3, sex: "f", notes: "Married Ramesh Macha." },
    { id: "tbd-subramanium", name: "Subramanium Emani", family: "emani",
      gen: 3, sex: "m" },
    { id: "tbd-swathi", name: "Swathi Makani", family: "tbd",
      marriedInto: "makani", gen: 3, sex: "f", todo: "birth family (intiperu)" },
    { id: "tbd-sujatha", name: "Sujatha Makani", family: "nanduri",
      marriedInto: "makani", gen: 3, sex: "f", todo: "birth family (intiperu)" },
    { id: "tbd-vijayabharathi", name: "Vijayabharathi Emani", family: "tbd",
      marriedInto: "emani", gen: 3, sex: "f" },
    { id: "tbd-indira", name: "Indira Maddala", family: "tbd",
      marriedInto: "maddala", gen: 3, sex: "f",
      todo: "birth family (intiperu)" },
    { id: "tbd-rajeshwari", name: "Rajeshwari Maddala", family: "tbd",
      marriedInto: "maddala", gen: 3, sex: "f",
      todo: "birth family (intiperu)" },
    { id: "tbd-kumari", name: "Kumari Maddala", family: "tbd",
      marriedInto: "maddala", gen: 3, sex: "f",
      todo: "birth family (intiperu)" },
    { id: "rao-appa", name: "Appa Rao", family: "tbd", gen: 3, sex: "m" },
    { id: "rao-mruthyunjaya", name: "Mruthyunjaya Rao", family: "tbd", gen: 3,
      sex: "m" },
    { id: "rao-appa-2", name: "Appa Rao", family: "tbd", gen: 3, sex: "m" },
    { id: "rayappareddy-appala", name: "Appala Narayana Rayappareddy",
      family: "tbd", gen: 3, sex: "m" },
    { id: "apparao-venkata", name: "Venkata Apparao", family: "tbd", gen: 3,
      sex: "m" },
    { id: "veerisetti-satyanarayana", name: "Satyanarayana Veerisetti",
      family: "veerisetti", gen: 3, sex: "m" },
    { id: "kosanam-uma", name: "Uma Maheshwar Rao Kosanam", family: "kosanam",
      gen: 3, sex: "m" },
    { id: "bhandar-nageshwar", name: "Nageshwar Rao Bhandar",
      family: "bhandar", gen: 3, sex: "m" },

    /* ---- generation 4 ---- */
    { id: "makani-kittu", name: "Krishna Chaitanya Makani", family: "makani",
      gen: 4, sex: "m", order: 1, nickname: "Kittu" },
    { id: "makani-sindhura", name: "Sindhura Makani", family: "makani",
      gen: 4, sex: "f", order: 1 },
    { id: "macha-hasini", name: "Hasini Macha", family: "macha", gen: 4,
      sex: "f", order: 1 },
    { id: "makani-krishna", name: "Krishna Tej Makani", family: "makani",
      gen: 4, sex: "m", order: 1 },
    { id: "makani-sai-priyanka", name: "Sai Priyanka Mutyala",
      family: "makani", marriedInto: "mutyala", gen: 4, sex: "f", order: 1,
      notes: "Born Sai Priyanka Makani; took the Mutyala name on marriage." },
    { id: "tbd-lakshmi", name: "Lakshmi Priya Makani", family: "emani",
      marriedInto: "makani", gen: 4, sex: "f", order: 1 },
    { id: "makani-shanthi", name: "Shanthi Priya Makani", family: "makani",
      gen: 4, sex: "f", order: 1 },
    { id: "makani-triveni", name: "Triveni", family: "makani", gen: 4,
      sex: "f", order: 1 },
    { id: "makani-leena", name: "Leena Priya Makani", family: "makani",
      gen: 4, sex: "f", order: 1 },
    { id: "maddala-prasanna", name: "Prasanna", family: "maddala", gen: 4,
      sex: "f", order: 1 },
    { id: "maddala-daughter", name: "Daughter?", family: "maddala", gen: 4,
      sex: "f", order: 1 },
    { id: "rao-uma", name: "Uma Maheshwar Rao", family: "tbd", gen: 4,
      sex: "m", order: 1 },
    { id: "rao-madhukar", name: "Madhukar", family: "tbd", gen: 4, sex: "m",
      order: 1 },
    { id: "tbd-jayanthi", name: "Jayanthi", family: "tbd", gen: 4, sex: "f",
      order: 1 },
    { id: "tbd-seethalu", name: "Seethalu", family: "tbd", gen: 4, sex: "f",
      order: 1 },
    { id: "tbd-ashok", name: "Ashok", family: "tbd", gen: 4, sex: "m",
      order: 1 },
    { id: "Chanthati-lavanya", name: "Lavanya", family: "Chanthati", gen: 4,
      sex: "f", order: 1 },
    { id: "Chanthati-praveen", name: "Praveen Chanthati", family: "Chanthati",
      gen: 4, sex: "m", order: 1 },
    { id: "makani-prathap", name: "Prathap", family: "makani", gen: 4,
      sex: "m", order: 1, alive: false },
    { id: "makani-ramakrishna", name: "Ramakrishna Makani", family: "makani",
      gen: 4, sex: "m", order: 2,
      notes: "Named after his father's youngest brother." },
    { id: "makani-pony", name: "Krishna Keerthan Makani", family: "makani",
      gen: 4, sex: "m", order: 2, nickname: "Pony" },
    { id: "makani-sri-vatsava", name: "Sri Vatsava Makani", family: "makani",
      gen: 4, sex: "m", order: 2 },
    { id: "macha-jessi", name: "Jessi Macha", family: "macha", gen: 4,
      sex: "f", order: 2 },
    { id: "makani-krishna-2", name: "Venkata Krishna Kanth Makani",
      family: "makani", gen: 4, sex: "m", order: 2 },
    { id: "emani-gowtham", name: "Gowtham Emani", family: "emani", gen: 4,
      sex: "m", order: 2 },
    { id: "makani-vamsi", name: "Vamsi Krishna Makani", family: "makani",
      gen: 4, sex: "m", order: 2 },
    { id: "makani-rakesh", name: "Rakesh Makani", family: "makani", gen: 4,
      sex: "m", order: 2 },
    { id: "makani-neelima", name: "Neelima Makani", family: "makani", gen: 4,
      sex: "f", order: 2 },
    { id: "maddala-dattu", name: "Dattu Maddala", family: "maddala", gen: 4,
      sex: "m", order: 2 },
    { id: "maddala-yashaswini", name: "Yashaswini", family: "maddala", gen: 4,
      sex: "f", order: 2 },
    { id: "tbd-lakshmi-2", name: "Lakshmi", family: "tbd", gen: 4, sex: "f",
      order: 2 },
    { id: "rao-jyothi", name: "Jyothi", family: "tbd", gen: 4, sex: "f",
      order: 2 },
    { id: "tbd-sujatha-2", name: "Sujatha", family: "tbd", gen: 4, sex: "f",
      order: 2 },
    { id: "tbd-ranga", name: "Ranga", family: "tbd", gen: 4, sex: "m",
      order: 2 },
    { id: "tbd-pradeep", name: "Pradeep", family: "tbd", gen: 4, sex: "m",
      order: 2 },
    { id: "Chanthati-anil", name: "Anil Chanthati", family: "Chanthati",
      gen: 4, sex: "m", order: 2 },
    { id: "Chanthati-priya", name: "Priya", family: "Chanthati", gen: 4,
      sex: "f", order: 2 },
    { id: "makani-pradeep", name: "Pradeep", family: "makani", gen: 4,
      sex: "m", order: 2 },
    { id: "makani-sneha", name: "Sneha Priya Makani", family: "makani",
      gen: 4, sex: "f", order: 3 },
    { id: "maddala-hari", name: "Hari Maddala", family: "maddala", gen: 4,
      sex: "m", order: 3 },
    { id: "tbd-ramesh", name: "Ramesh", family: "tbd", gen: 4, sex: "m",
      order: 3 },
    { id: "rao-bharathi", name: "Bharathi", family: "tbd", gen: 4, sex: "f",
      order: 3 },
    { id: "tbd-santhosh-2", name: "Santhosh", family: "tbd", gen: 4, sex: "m",
      order: 3 },
    { id: "tbd-aruna", name: "Aruna", family: "tbd", gen: 4, sex: "f",
      order: 3 },
    { id: "tbd-daughter", name: "Daughter?", family: "tbd", gen: 4, sex: "f",
      order: 4 },
    { id: "rao-sudhakar", name: "Sudhakar", family: "tbd", gen: 4, sex: "m",
      order: 4 },
    { id: "mutyala-thrinadh", name: "Thrinadh Mutyala", family: "mutyala",
      gen: 4, sex: "m",
      todo: "his parents and siblings - a new branch to grow" },
    { id: "tbd-soumya", name: "Soumya Makani", family: "modugu",
      marriedInto: "makani", gen: 4, sex: "f" },
    { id: "tbd-navya", name: "Navya Nagashree Makani", family: "tbd",
      marriedInto: "makani", gen: 4, sex: "f", todo: "birth family (intiperu)" },
    { id: "tbd-vinodh", name: "Vinodh", family: "reddy", gen: 4, sex: "m" },
    { id: "tbd-sugumar", name: "Sugumar", family: "tbd", gen: 4, sex: "m" },
    { id: "tbd-nidhi", name: "Nidhi Makani", family: "thota",
      marriedInto: "makani", gen: 4, sex: "f", todo: "birth family (intiperu)" },
    { id: "tbd-santhosh", name: "Santhosh", family: "tbd", gen: 4, sex: "m",
      todo: "birth family (intiperu)" },
    { id: "tbd-swetha", name: "Swetha Makani", family: "tbd",
      marriedInto: "makani", gen: 4, sex: "f", todo: "birth family (intiperu)" },

    /* ---- generation 5 ---- */
    { id: "makani-hanvika", name: "Hanvika Makani", family: "makani", gen: 5,
      sex: "f", order: 1 },
    { id: "makani-mokshith", name: "Mokshith Makani", family: "makani",
      gen: 5, sex: "m", order: 1 },
    { id: "makani-kriti", name: "Kriti Sahasra Makani", family: "makani",
      gen: 5, sex: "f", order: 1 },
    { id: "tbd-aira", name: "Aira", family: "tbd", gen: 5, sex: "u", order: 1 },
    { id: "makani-tanvi", name: "Tanvi Makani", family: "makani", gen: 5,
      sex: "f", order: 1 },
    { id: "makani-srihan", name: "Srihan Makani", family: "makani", gen: 5,
      sex: "m", order: 1 },
    { id: "makani-ruhika", name: "Ruhika Makani", family: "makani", gen: 5,
      sex: "f", order: 2 },
    { id: "tbd-sia", name: "Sia", family: "tbd", gen: 5, sex: "u", order: 2 },
    { id: "makani-rudra", name: "Rudra Makani", family: "makani", gen: 5,
      sex: "m", order: 2 }
  ],

  unions: [
    { id: "u-makani-g1", partners: ["makani-g1-f", "makani-g1-m"],
      children: ["makani-ramachandra-rao", "makani-sanjeeva", "makani-nageshwara", "sunkara-chitamma", "makani-sarojini"] },
    { id: "u-macha-g1", partners: ["macha-g1-f", "macha-g1-m"],
      children: ["macha-thatha"] },
    { id: "u-makani-g2",
      partners: ["makani-ramachandra-rao", "tbd-padmavathi"],
      children: ["makani-venkateshwara-rao", "makani-chandrashekhar", "makani-satyanarayana", "makani-nagarjuna-sagar", "makani-harikrishna", "makani-ramakrishna-sr"],
      notes: "Six sons, no daughters recorded.", todo: "were there daughters?" },
    { id: "u-macha-g2", partners: ["macha-thatha", "tbd-jayalakshmi"],
      children: ["macha-padmaja", "macha-suneetha", "macha-ramesh"] },
    { id: "u-venkateshwara-latha",
      partners: ["makani-venkateshwara-rao", "tbd-latha"],
      children: ["makani-kittu", "makani-pony"] },
    { id: "u-chandrashekhar-sarada",
      partners: ["makani-chandrashekhar", "tbd-sarada"],
      children: ["makani-sindhura", "makani-sri-vatsava"] },
    { id: "u-satyanarayana-padmaja",
      partners: ["makani-satyanarayana", "macha-padmaja"],
      children: ["makani-krishna", "makani-krishna-2"],
      notes: "First of the two Makani-Macha marriages.",
      todo: "children of Satyanarayana and Padmaja" },
    { id: "u-nagarjuna-suneetha",
      partners: ["makani-nagarjuna-sagar", "macha-suneetha"],
      children: ["makani-ramakrishna", "makani-sai-priyanka"],
      notes: "Second Makani-Macha marriage. Nagarjuna Sagar is Satyanarayana's younger brother and Suneetha is Padmaja's younger sister, so the children of these two couples are double first cousins." },
    { id: "u-ramesh-nalini", partners: ["macha-ramesh", "tbd-nalini"],
      children: ["macha-hasini", "macha-jessi"] },
    { id: "u-thrinadh-priyanka",
      partners: ["mutyala-thrinadh", "makani-sai-priyanka"], children: [],
      todo: "wedding year" },
    { id: "u-krishna-soumya", partners: ["makani-krishna", "tbd-soumya"],
      children: ["makani-hanvika", "makani-ruhika"] },
    { id: "u-krishna-2-lakshmi",
      partners: ["makani-krishna-2", "tbd-lakshmi"],
      children: ["makani-kriti"] },
    { id: "u-subramanium-x",
      partners: ["tbd-subramanium", "tbd-vijayabharathi"],
      children: ["tbd-lakshmi", "emani-gowtham"] },
    { id: "u-kittu-navya", partners: ["makani-kittu", "tbd-navya"],
      children: ["makani-mokshith"] },
    { id: "u-sindhura-vinodh", partners: ["tbd-vinodh", "makani-sindhura"],
      children: [] },
    { id: "u-nageshwara-x", partners: ["makani-nageshwara", "tbd-vijayamma"],
      children: ["makani-ramamohan", "makani-madhumohan", "makani-vijayanand"] },
    { id: "u-ramamohan-swathi", partners: ["makani-ramamohan", "tbd-swathi"],
      children: ["makani-shanthi", "makani-vamsi"] },
    { id: "u-madhumohan-sujatha",
      partners: ["makani-madhumohan", "tbd-sujatha"],
      children: ["makani-triveni", "makani-rakesh"] },
    { id: "u-vijayanand-x", partners: ["makani-vijayanand"],
      children: ["makani-leena", "makani-neelima", "makani-sneha"] },
    { id: "u-shanthi-sugumar", partners: ["tbd-sugumar", "makani-shanthi"],
      children: [] },
    { id: "u-vamsi-nidhi", partners: ["makani-vamsi", "tbd-nidhi"],
      children: ["makani-tanvi", "makani-rudra"] },
    { id: "u-triveni-santhosh", partners: ["tbd-santhosh", "makani-triveni"],
      children: ["tbd-aira", "tbd-sia"] },
    { id: "u-rakesh-swetha", partners: ["makani-rakesh", "tbd-swetha"],
      children: ["makani-srihan"] },
    { id: "u-sanjeeva-sathyavathi",
      partners: ["makani-sanjeeva", "tbd-sathyavathi"],
      children: ["makani-anu", "makani-meena", "makani-bujji", "makani-baby-2"] },
    { id: "u-narayanamma-x", partners: ["makani-narayanamma"],
      children: ["maddala-jayalakshmi", "Chanthati-seetharathnamma"] },
    { id: "u-seetharathnamma-apparao",
      partners: ["Chanthati-seetharathnamma", "tbd-apparao"],
      children: ["Chanthati-nagamani", "Chanthati-indira", "Chanthati-usha", "Chanthati-chanti-amma", "Chanthati-bujjiamma", "Chanthati-jagan", "Chanthati-nageswar"] },
    { id: "u-jayalakshmi-veera",
      partners: ["maddala-jayalakshmi", "tbd-veera"],
      children: ["maddala-srinivas", "maddala-shekhar", "maddala-ramakanth"] },
    { id: "u-srinivas-indira", partners: ["maddala-srinivas", "tbd-indira"],
      children: ["maddala-prasanna", "maddala-dattu"] },
    { id: "u-shekhar-rajeshwari",
      partners: ["maddala-shekhar", "tbd-rajeshwari"], children: [] },
    { id: "u-ramakanth-kumari", partners: ["maddala-ramakanth", "tbd-kumari"],
      children: ["maddala-daughter", "maddala-yashaswini", "maddala-hari"] },
    { id: "u-nagamani-appa", partners: ["rao-appa", "Chanthati-nagamani"],
      children: ["tbd-ramesh", "rao-uma", "tbd-lakshmi-2", "tbd-daughter"] },
    { id: "u-indira-mruthyunjaya",
      partners: ["rao-mruthyunjaya", "Chanthati-indira"],
      children: ["rao-madhukar", "rao-jyothi", "rao-bharathi", "rao-sudhakar"] },
    { id: "u-usha-appa-2", partners: ["rao-appa-2", "Chanthati-usha"],
      children: ["tbd-jayanthi", "tbd-kumari", "tbd-sujatha-2", "tbd-santhosh-2"] },
    { id: "u-chanti-amma-appala",
      partners: ["rayappareddy-appala", "Chanthati-chanti-amma"],
      children: ["tbd-seethalu", "tbd-ranga", "tbd-aruna"] },
    { id: "u-bujjiamma-venkata",
      partners: ["apparao-venkata", "Chanthati-bujjiamma"],
      children: ["tbd-ashok", "tbd-pradeep"] },
    { id: "u-jagan-x", partners: ["Chanthati-jagan"],
      children: ["Chanthati-lavanya", "Chanthati-anil"] },
    { id: "u-nageswar-x", partners: ["Chanthati-nageswar"],
      children: ["Chanthati-praveen", "Chanthati-priya"] },
    { id: "u-chitamma-bhushan", partners: ["sunkara-chitamma", "tbd-bhushan"],
      children: ["sunkara-srinu", "sunkara-ashok"] },
    { id: "u-anu-x", partners: ["bhandar-nageshwar", "makani-anu"],
      children: ["makani-prathap", "makani-pradeep"] },
    { id: "u-sarojini-nagabhushan",
      partners: ["makani-sarojini", "rao-nagabhushan"],
      children: ["makani-neelima-2", "makani-praveen"] },
    { id: "u-meena-satyanarayana",
      partners: ["veerisetti-satyanarayana", "makani-meena"], children: [] },
    { id: "u-baby-2-uma", partners: ["kosanam-uma", "makani-baby-2"],
      children: [] }
  ]
};
